# CollectionBuilder 
# Jekyll Digital Collection Generator

# URL variables
# site domain 
url: https://www.ijc.uidaho.edu
# location on the domain
# e.g. /digital/hjccc
baseurl: /ijcw
# CONTENTdm server url
cdm-url: https://digital.lib.uidaho.edu
# location of code
source-code: https://github.com/CollectionBuilder

# Site settings
title: Joe Williams Collection 
# header and head metadata
tagline: Digital Collection Magic with Static Web Technologies
description: Joe Williams, vocalist, was born Joseph Goreed in Cordele, Georgia on December 12, 1918. His family moved to Chicago when he was three. He began singing professionally in the late 1930s, and during WW II was vocalist for the big bands of Coleman Hawkins and Lionel Hampton. After the war he sang with other bands, including a stint with Count Basie. He would return to the Basie band in 1954 and remain with it until 1960. With Basie, Williams had his first recording hits, including "Everyday" and "Alright, Okay, You Win." He toured extensively in the 1960s, from Chicago, and continued to tour after a move to Las Vegas in the early 1970s. He sang blues, jazz, and popular ballads, recorded much, and won many awards and wide recognition for his singing. In the 1980s he had a recurring role (as "Grandpa Al") on TV's The Cosby Show. He died in Las Vegas on March 29, 1999.
# Organization branding
organization-name: "Digital Initiatives, University of Idaho Library"
organization-link: https://www.lib.uidaho.edu/digital/
organization-logo-banner: https://www.lib.uidaho.edu/media/digital/justdi_logo_sm.png
organization-logo-nav: https://www.lib.uidaho.edu/media/digital/bannerlogo_allwhite.png

# Collection settings
# contentdm collection name 
cdm-collection-id: ijcw
# name of metadata file, be sure to also change page_gen data setting!
metadata: ijcw 
# page gen settings 
# "data" value must be the name of the metadata file
page_gen:
  - data: 'ijcw'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html'   

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# if present, used to add analytics during build
google-analytics-id: UA-76328753-1

# add liquid profiler to id bottlenecks
# profile: true

exclude: [docs/, Rakefile, README.md, LICENSE]

# compress CSS output
sass:
  style: compressed
