# CollectionBuilder 
# Jekyll Digital Collection Generator

# URL variables
# site domain 
url: https://www.lib.uidaho.edu
# location on the domain
# e.g. /digital/hjccc
baseurl: /ijcag
# CONTENTdm server url
cdm-url: https://digital.lib.uidaho.edu
# location of code
source-code: https://github.com/CollectionBuilder

# Site settings
title: Al Grey/Rosalie Soladar Memorial Collection
# header and head metadata
tagline: '"His signature was the plunger mute, and he used it swaggeringly..."'
description: "Albert Thornton Al Grey was born on June 6, 1925 and was raised in Pottstown, Pennsylvania. The son of a musician, Al began playing trombone, among other instruments, as a young boy. Though he played other instruments (tuba among them) briefly, during service in World War II, he finally settled on the trombone. After the war he began playing and recording with Benny Carter's Big Band, and then with Lionel Hampton's band (1948-1952), where he began using a plunger as a mute. He also worked as a studio musician for Decca in the early 1950s. As the demand for the big band sound waned, he worked with a variety of small groups, settling in with the Count Basie Orchestra between 1957 and 1961, left it briefly and then was part of it from 1964 to 1977. Subsequent to that he again played and recorded with a variety of ensembles. He was active in music until his death in March of 2000."
# Organization branding
organization-name: "Digital Initiatives, University of Idaho Library"
organization-link: https://www.lib.uidaho.edu/digital/
organization-logo-banner: https://www.lib.uidaho.edu/media/digital/justdi_logo_sm.png
organization-logo-nav: https://www.lib.uidaho.edu/media/digital/bannerlogo_allwhite.png

# Collection settings
# contentdm collection name 
cdm-collection-id: ijcag
# name of metadata file, be sure to also change page_gen data setting!
metadata: ijcag 
# page gen settings 
# "data" value must be the name of the metadata file
page_gen:
  - data: 'ijcag'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html'   

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# if present, used to add analytics during build
google-analytics-id: 

# add liquid profiler to id bottlenecks
# profile: true

exclude: [docs/, Rakefile, README.md, LICENSE]

# compress CSS output
sass:
  style: compressed
