# CollectionBuilder 
# Jekyll Digital Collection Generator

# URL variables
# site domain 
url: https://www.ijc.uidaho.edu
# location on the domain
# e.g. /digital/hjccc
baseurl: /psychiana
# CONTENTdm server url
cdm-url: https://digital.lib.uidaho.edu
# location of code
source-code: https://github.com/CollectionBuilder

# Site settings
title: Lee Morse International Jazz Collection 
# header and head metadata
tagline: Digital Collection Magic with Static Web Technologies
description: "Lena Corinne Taylor was born on November 30, 1897 to Pleasant John and Olive Taylor. In 1908 her family moved to Kooskia, Idaho. She gained fame as a vaudeville performer, and critics were impressed by Lee’s vocal range. Lee was one of the most recorded female vocalists of the 1920s.

In the mid-1930s, Lee opened a small club in Texas, which a fire destroyed in 1939. She resettled in Rochester, NY. She revitalized her career in a limited way there. She died suddenly in 1954 at the age of 57."
organization-name: "Digital Initiatives, University of Idaho Library"
organization-link: https://www.lib.uidaho.edu/digital/
organization-logo-banner: https://www.lib.uidaho.edu/media/digital/justdi_logo_sm.png
organization-logo-nav: https://www.lib.uidaho.edu/media/digital/bannerlogo_allwhite.png

# Collection settings
# contentdm collection name 
cdm-collection-id: ijclm
# name of metadata file, be sure to also change page_gen data setting!
metadata: ijclm 
# page gen settings 
# "data" value must be the name of the metadata file
page_gen:
  - data: 'ijclm'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html'   

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# if present, used to add analytics during build
google-analytics-id: UA-76328753-1

# add liquid profiler to id bottlenecks
# profile: true

exclude: [docs/, Rakefile, README.md, LICENSE]

# compress CSS output
sass:
  style: compressed
