# CollectionBuilder 
# Jekyll Digital Collection Generator

# URL variables
# site domain 
url: https://www.ijc.uidaho.edu
# location on the domain
# e.g. /digital/hjccc
baseurl: /psychiana
# CONTENTdm server url
cdm-url: https://digital.lib.uidaho.edu
# location of code
source-code: https://github.com/CollectionBuilder

# Site settings
title: Lee Morse International Jazz Collection 
# header and head metadata
tagline: Digital Collection Magic with Static Web Technologies
description: "Born Lena Corinne Taylor, Lee Morse gained fame as a vaudeville performer. She was one of the most widely recorded voices of the 1920s. Lee Morse died suddenly in 1954 atthe age of 57"
organization-name: "Digital Initiatives, University of Idaho Library"
organization-link: https://www.lib.uidaho.edu/digital/
organization-logo-banner: https://www.lib.uidaho.edu/media/digital/justdi_logo_sm.png
organization-logo-nav: https://www.lib.uidaho.edu/media/digital/bannerlogo_allwhite.png

# Collection settings
# contentdm collection name 
cdm-collection-id: ijclm
# name of metadata file, be sure to also change page_gen data setting!
metadata: ijclm 
# page gen settings 
# "data" value must be the name of the metadata file
page_gen:
  - data: 'ijclm'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html'   

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# if present, used to add analytics during build
google-analytics-id: UA-76328753-1

# add liquid profiler to id bottlenecks
# profile: true

exclude: [docs/, Rakefile, README.md, LICENSE]

# compress CSS output
sass:
  style: compressed
