# CollectionBuilder 
# Jekyll Digital Collection Generator

# URL variables
# site domain 
url: https://www.ijc.uidaho.edu
# location on the domain
# e.g. /digital/hjccc
baseurl: /psychiana
# CONTENTdm server url
cdm-url: https://digital.lib.uidaho.edu
# location of code
source-code: https://github.com/CollectionBuilder

# Site settings
title: Leonard Feather Jazz Collection 

# header and head metadata
tagline: Digital Collection Magic with Static Web Technologies
description: Jazz journalist Leonard Geoffrey Feather was born in Hampstead, England on September 13, 1914. In the 1930s, he arranged, composed, and produced jazz sessions, and began to write about jazz for print media.  After moving to New York he worked with such greats as Louis Armstrong, Dizzy Gillespie, and Duke Ellington, establishing his reputation in various fields of jazz.  Writing for famous jazz journals and authoring several books, he was particularly influential in promoting Bebop.  Moving to Los Angeles in 1960, he became the chief jazz critic for the Los Angeles Times. Leonard Feather died on September 22, 1994.

 
# Organization branding
organization-name: "Digital Initiatives, University of Idaho Library"
organization-link: https://www.lib.uidaho.edu/digital/
organization-logo-banner: https://www.lib.uidaho.edu/media/digital/justdi_logo_sm.png
organization-logo-nav: https://www.lib.uidaho.edu/media/digital/bannerlogo_allwhite.png

# Collection settings
# contentdm collection name 
cdm-collection-id: lfc
# name of metadata file, be sure to also change page_gen data setting!
metadata: lfc 
# page gen settings 
# "data" value must be the name of the metadata file
page_gen:
  - data: 'lfc'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html'   

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# if present, used to add analytics during build
google-analytics-id: UA-76328753-1

# add liquid profiler to id bottlenecks
# profile: true

exclude: [docs/, Rakefile, README.md, LICENSE]

# compress CSS output
sass:
  style: compressed
